cart/urls.py
from django.urls import path

from .views import *

app_name="cart"

urlpatterns = [
    path("",CartIndexView.as_view(),name="cart"),
    path("add/<int:product_id>",AddToCartView.as_view(),name="add-cart"),
    path("remove/<int:product_id>",RemoveToCartView.as_view(),name="remove-cart"),
]

core/urls.py
from django.urls import path,include

from .views import *
app_name="core"

urlpatterns = [
    path("",IndexView.as_view(),name="index"),
    path("login/",Login,name="login"),
    path("sign_up/",Sign_Up,name="sign_up"),
    path("logout/",Logout,name="logout"),
    path("user_setting/",UserSetting,name="user_setting")
]

crud/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns =[
    path('admin/', admin.site.urls),
]
urlpatterns +=  [
    path('',include('product.urls')),
     path('restapi/',include('restapi.urls')),
   
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns = [
#     path('',include('product.urls')),
#     path('admin/', admin.site.urls),
   
# ]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls',namespace='core')),
    path('product/', include('product.urls',namespace="product")),
    path("cart/",include("cart.urls",namespace="cart")),
    path("recommend/",include("recommend.urls",namespace="recommend"))

]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns+=staticfiles_urlpatterns()

core/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class EcommerceUser(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name="ecommerce_user")
    isSeller=models.BooleanField(default=False)

core/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
from django.views.generic import View,ListView,DetailView,UpdateView,CreateView
from product.models import Product
from cart.models import Cart
from .models import EcommerceUser

from django.core.paginator import Paginator

import pandas as pd

import numpy as np

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity


class IndexView(ListView):
    model=Product
    template_name="product/index.html"

    def get(self,request, *args,**kwargs):
        user=request.user

        ecommerce_user=""

        if user.is_authenticated:
            ecommerce_user=user.ecommerce_user

        next_page=1
        prev_page=0
        recommendation=[]
        query=Product.objects.all()
        if("search_query" in request.GET):
            search_query=request.GET["search_query"]
            query=Product.objects.filter(product_name__contains=search_query)       
            recommendation=getRecommendation(query[0],10)
    



        p=Paginator(query,10)

        page_num=1

        if "page" in request.GET:
            page_num=request.GET["page"]
        
        page=p.page(page_num)

        next_page=page.next_page_number()
               

        context={
            "page_title":"Homepage",
            "user":user,
            "products":page.object_list,
            "ecommerce_user":ecommerce_user,
            "next_page":next_page,
            "recommendation":recommendation
        }

        return render(request,self.template_name, context=context)
    

def Login(req):

    if req.user.is_authenticated:
            return redirect("core:index")

    if req.method=="GET":
        context={
            "page_title":"login"
        }
        return render(req,"core/login.html",context=context)
    else:
        username=req.POST["username"]
        password=req.POST["password"]
        user=authenticate(username=username,password=password)
        if(user!=None):
            login(req,user)
            return redirect("core:index")
        else:
            return redirect("core:login")



def Sign_Up(req):
    if req.user.is_authenticated:
            return redirect("core:index")

    if req.method=="GET":
        context={
            "page_title":"Sign Up"
        }
        return render(req,"core/sign_up.html",context=context)
    else:
        username=req.POST["username"]
        password=req.POST["password"]
        email=req.POST["email"]

        user=User.objects.create_user(email=email,username=username,password=password)
        user.save()

        ecommerce_user=EcommerceUser(user=user,isSeller=False)
        ecommerce_user.save()

        return redirect("core:login")

def UserSetting(req):

    user=req.user

    if not req.user.is_authenticated:
            return redirect("core:index")

    if req.method=="POST":
        ecommerce_user=EcommerceUser.objects.get(user__id=req.user.id)
        
        ecommerce_user.isSeller=True if ("isSeller" in req.POST) else (False)
        ecommerce_user.save()
        return redirect("core:user_setting")
    else:
        context={
            "page_title":"User Setting",
            "user":req.user,
            "ecommerce_user":user.ecommerce_user.all()[0]

        }
        return render(req,"core/setting.html",context=context)
        
def Logout(req):
    logout(req)
    return redirect("core:login")



def getRecommendation(search_term,number_of_recommendation):

    id=(search_term.id)

    products=Product.objects.all()

    df=pd.DataFrame(products.values("id","product_description"))

    cv=CountVectorizer(tokenizer=lambda doc: doc, lowercase=False)
    
    count_matrix=cv.fit_transform(df["product_description"]) 
    cosine_sim=cosine_similarity(count_matrix)

    similar_foods=list(enumerate(cosine_sim[id-1]))

    sorted_similar_food = sorted(similar_foods,key=lambda x:x[1],reverse=True)
    
    i=0
    recommendation=[]
    for element in sorted_similar_food:
        try:
            print(element[0])
            recommendation.append(Product.objects.get(id=element[0]))
        except:
            continue
        i=i+1
        if i > number_of_recommendation:
            break
    return recommendation

templates/core/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <title>Food Recommendation</title>
  </head>
  <body>
  <nav class="navbar navbar-expand-sm navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'core:index'%}">Local </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link " aria-current="page" href="{% url 'core:index'%}">Home</a>
        </li>
         {% if  not user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href='{% url "core:login"%}'>Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href='{% url "core:sign_up"%}'>Signup</a>
        </li>
        {% else %}
        {% if ecommerce_user.isSeller  %}
        <li class="nav-item">
        <a class="nav-link" aria-current="page" href='{% url "product:product_index" %}'>Product</a>
        </li>
        {% endif %}
        <li class="nav-item">
        <a class="nav-link" aria-current="page" href='{% url "core:logout" %}'>Logout</a>
        </li>

        <li class="nav-item">
        <a class="nav-link" aria-current="page" href='{% url "cart:cart"%}'>Cart</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" aria-current="page" href='{% url "core:user_setting" %}'>Setting</a>
        </li>

        {% endif %}

        
      </ul>

      <form class="d-flex">
        <input class="form-control me-2" type="text" name="search_query" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>


    </div>
  </div>
</nav>
     {% block content %}
        
    {% endblock %}
  </body>
</html>

templates/core/index.html
{%extends 'core/base.html' %}

{% block content%}
    <h1>Homepage</h1>
{% endblock %}

templates/core/login.html
{%extends 'core/base.html' %}

{% block content%}
<div class="container-sm">
  <!-- Content here -->
<br>
<br>
<br>
<h1>Login</h1>
<br>

 <form method="POST"}>
 {% csrf_token %}
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Username</label>
    <input name="username" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input name="password" type="password" class="form-control" id="exampleInputPassword1">
  </div>
  <div class="mb-3 form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div>
  <button type="submit" class="btn btn-primary">Login</button>
</form>
</div>
{% endblock %}

templates/core/setting.html
{%extends 'core/base.html' %}

{% block content%}
    <h1>Setting</h1>

    <form action="{% url 'core:user_setting' %}" method="POST">
    {% csrf_token %}
        <input type="checkbox" name="isSeller" selected={{user.ecommerce_user.isSeller}}/> is Seller
        <input type="submit"/>
    </form>
{% endblock %}

templates/core/sign_up.html
{%extends 'core/base.html' %}

{% block content%}
<div class="container-sm">
  <!-- Content here -->
<br>
<br>
<br>
<h1>Signup</h1>
<br>

 <form method="POST">
 {% csrf_token %}
   <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Email address</label>
    <input type="email" name="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
  </div>
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Username</label>
    <input name="username" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input name="password" type="password" class="form-control" id="exampleInputPassword1">
  </div>
  <div class="mb-3 form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div>
  <button type="submit" class="btn btn-primary">Signup</button>
</form>
</div>
{% endblock %}