cart/urls.py
from django.urls import path

from .views import *

app_name="cart"

urlpatterns = [
    path("",CartIndexView.as_view(),name="cart"),
    path("add/<int:product_id>",AddToCartView.as_view(),name="add-cart"),
    path("remove/<int:product_id>",RemoveToCartView.as_view(),name="remove-cart"),
]

crud/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns =[
    path('admin/', admin.site.urls),
]
urlpatterns +=  [
    path('',include('product.urls')),
     path('restapi/',include('restapi.urls')),
   
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns = [
#     path('',include('product.urls')),
#     path('admin/', admin.site.urls),
   
# ]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls',namespace='core')),
    path('product/', include('product.urls',namespace="product")),
    path("cart/",include("cart.urls",namespace="cart")),
    path("recommend/",include("recommend.urls",namespace="recommend"))

]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns+=staticfiles_urlpatterns()

product/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("home/", view_index, name="home"),
    path("product/", view_add_product),
    path("product/save", view_productdata_save),
    path("product/productlist", view_product_lists, name="productlist"),
    path("product/edit/<int:ID>", view_productdata_updateform),
    path("product/edit/update/<int:ID>", view_update_form_data_in_db),
    path("product/delete/<int:ID>", view_delete),
    # path('user/register', view_login_page),
    path("signup/", view_register_user, name="signup"),
    path("restrictpage/", view_authenticate_user, name="login"),
    path("welcome/", view_logout_request, name="logout"),
    path("our-product/", view_our_product, name="ourproduct"),
    path("search/", view_search, name="search"),
    path("file-upload/", view_upload, name="upload"),
    path("file-upload/upload", view_upload_pic),
    path("contact/", view_contact, name="contact"),
    path("view-uploaded-files/", view_uploaded_files, name="uploaded-files"),
]

product/models.py
from django.db import models
from django.contrib.auth.models import User


class file(models.Model):
  file=models.ImageField(upload_to="media")
# Create your models here.
class Product(models.Model):
    product_name = models.CharField(max_length=200)
    product_code = models.CharField(max_length=10)
    product_price = models.CharField(max_length=10)
    product_image=models.ImageField(upload_to="product_image")
    
    def __str__(self):
        return self.product_name

    def check_valid_format_of_code(self):
      if self.product_code == 'CharField':
        return True
      else:
        return False
    
    def check_valid_product_price(self):
      if self.product_price > 100:
        print("product available")
        return True
      else :

        return False


    

class customerDetail(models.Model):
    customer_name=models.ForeignKey(User, default=1, on_delete=models.SET_DEFAULT)
    customer_address=models.CharField(max_length=200)
    customer_contact=models.CharField(max_length=200)
    
    def __str__(self):
        return self.customer_name
      
    def check_total_contact_list(self):
      if self.customer_contact > 20:
        print("max contact")
        return True
      else:
        print("min contact")
        return False
    
    def check_contact_detail_of_customer(self):
      return self.customer_address

product/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import Template, Context
from .models import Product, file
from django.contrib.auth.models import User
from django.db.models import Q
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
def view_add_product(request):
    return render(request, "add_product.html")


def view_index(request):
    list_of_products = Product.objects.all()[:3]
    context_variable = {"products": list_of_products}

    return render(request,"index.html", context_variable)


def view_product_lists(request):
    list_of_products = Product.objects.all()
    context_variable = {"products": list_of_products}
    return render(request, "display_product.html", context_variable)


def view_productdata_save(request):
    if request.method == "POST":
        # get_all = request.POST
        get_name = request.POST["product_name"]

        get_code = request.POST["product_code"]
        get_price = request.POST["product_price"]
        # get_image = request.POST['product_image']
        # img = request.FILES['product_image']
        # Bookfile = file(product_image = img)
        # Bookfile.save()
        product_obj = Product(
            product_name=get_name, product_code=get_code, product_price=get_price
        )
        product_obj.save()
        return HttpResponse("Record saved")
    else:
        return HttpResponse("Error record saving")


def view_productdata_updateform(request, ID):

    product_obj = Product.objects.get(id=ID)

    context_varible = {"product": product_obj}
    return render(request, "update_product.html", context_varible)


def view_update_form_data_in_db(request, ID):
    product_obj = Product.objects.get(id=ID)

    product_form_data = request.POST

    product_obj.product_name = request.POST["product_name"]
    product_obj.product_code = request.POST["product_code"]
    product_obj.product_price = request.POST["product_price"]
    # product_obj.product_image = request.POST['product_image']

    product_obj.save()
    return HttpResponse("Record Updated!!")


def view_delete(request, ID):
    product_obj = Product.objects.get(id=ID)
    product_obj.delete()
    return HttpResponse("deleted")


def view_login_page(request):
    return render(request, "register_user.html")


def view_register_user(request):
    if request.method == "GET":
        return render(request, "register_user.html")
    else:
        print(request.POST)
        user = User.objects.create_user(
            username=request.POST["input_username"],
            password=request.POST["input_password"],
            email=request.POST["input_email"],
        )
        user.save()
        return render(request, "add_product.html")


@csrf_exempt
def view_authenticate_user(request):

    if request.method == "GET":
        return render(request, "login.html")
    elif request.method == "POST":
        print(request.POST)
        user = authenticate(
            username=request.POST["input_username"],
            password=request.POST["input_password"],
        )
        print(user)
        if user is not None:

            login(request, user)
            list_of_products = Product.objects.all()
            context_variable = {"products": list_of_products}

            return render(request, "page.html", context_variable)
        else:
            return HttpResponse("Authentication Failed")
    else:
        return HttpResponse("asdsadsad")


# def view_logout(request):
#     try:
#         del request.session['input_username']
#     except:
#     pass
#     return render(request, 'login.html')


def view_logout_request(request):
    logout(request)
    return render(request, "index.html")


def view_our_product(request):
    list_of_products = Product.objects.all()
    context_variable = {"products": list_of_products}

    return render(request, "product.html", context_variable)


# def view_search(request):
#     print(request.method)
#     print(request.GET)
#     if request.method=='GET':
#         input=request.GET['search']
#         match=Product.objects.filter(Q(product_name__startswith=input))
#         if match:
#             return render(request,'search.html',{'source':match})
#         else:
#             return HttpResponse('not found')
#     else: return HttpResponse('error')


def view_search(request):
    if request.method == "POST":
        srh = request.POST["search"]

        if srh:
            match = Product.objects.filter(product_name__icontains=srh)

            if match:
                return render(request, "search.html", {"sr": match})
            else:
                return HttpResponse("Item Not found")
        else:
            return "Not success"
    else:
        return render(request, "search.html")


def view_upload(request):
    return render(request, "upload.html")


def view_uploaded_files(request):
    list_of_files = file.objects.all()
    context_variable = {"files": list_of_files}

    return render(request, "display_files.html", context_variable)


def view_upload_pic(request):

    img = request.FILES["file"]
    print(img)
    Bookfile = file(file=img)
    Bookfile.save()
    return HttpResponse("File Uploaded!!")


def view_contact(request):
    return render(request, "contact.html")

templates/product/add_product.html
{%extends 'core/base.html' %}

{% block content%}
    <h1>Add Product</h1>
    <form method="POST" action="" enctype="multipart/form-data">
    {% csrf_token %}
        <input type="text" placeholder="Enter Product Name" name="product_name"/>
        <input type="textarea" placeholder="Enter Product Description" name="product_description"/>
        <input type="number" placeholder="Enter Product Price" name="product_price"/>
        <input type="slug" placeholder="Enter Product Slug" name="product_slug"/>
        <input type="File" placeholder="Enter Product Image" name="product_image"/>

        <input type="Submit"/>


    </form>
{% endblock %}

templates/product/edit_product.html
{%extends 'core/base.html' %}

{% block content%}
    <h1>Update Product</h1>
    <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}

        <input type="text" placeholder="Enter Product Name" name="product_name" value={{prd.product_name}}/>
        <input type="textarea" placeholder="Enter Product Description" name="product_description" value={{prd.product_description}}/>
        <input type="number" placeholder="Enter Product Price" name="product_price" value={{prd.product_price}}/>
        <input type="slug" placeholder="Enter Product Slug" name="product_slug" value={{prd.slug}}/>
        <input type="File" placeholder="Enter Product Image" name="product_image"/>
        <img src="/media/{{prd.product_image}}"/>

        <input type="Submit"/>


    </form>
{% endblock %}

templates/product/index.html
{% extends 'core/base.html' %}

{% block content%}

<div class="container d-flex mt-10">
  {% if user.ecommerce_user.isSeller %}
      <a class="btn btn-primary" href="{% url 'product:add_product'%}">Add New Product</a>
  {% endif %}

<div class="row">
<h2>Search Result</h2>
 {% for prd in products %}
  <div class="card" style="width: 18rem; margin-right:2rem">
    <img src="{{prd.product_image}}" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">{{prd.product_name}}</h5>
    </div>
    <ul class="d-flex">
      <a href="{{ prd.get_absolute_url }}"class="card-link">View Details</a>

      <a href="{% url 'cart:add-cart' prd.id%}" class="card-link">Add To Cart</a>
    </ul>
    {% if user.id == prd.owner.id%}
    <div class="card-body">
      <a href="{% url 'product:update_product' prd.id %}" class="card-link">Edit</a>
      <a href="{% url 'product:delete_product' prd.id %}" class="card-link">Delete</a>
    </div>
    {% endif %}
</div>
    {% endfor %}

</div>

<div class="container d-flex mt-10">

<div class="row">
 <h2>Recommendation</h2>
 
 {% for prd in recommendation %}

 {{prd}}
  <div class="card" style="width: 18rem; margin-right:2rem">
    <img src="{{prd.product_image}}" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">{{prd.product_name}}</h5>
    </div>
    <ul class="d-flex">
      <a href="{{ prd.get_absolute_url }}"class="card-link">View Details</a>

      <a href="{% url 'cart:add-cart' prd.id%}" class="card-link">Add To Cart</a>
    </ul>
    {% if user.id == prd.owner.id%}
    <div class="card-body">
      <a href="{% url 'product:update_product' prd.id %}" class="card-link">Edit</a>
      <a href="{% url 'product:delete_product' prd.id %}" class="card-link">Delete</a>
    </div>
    {% endif %}
</div>
    {% endfor %}



  <form method="GET">
    <input type="hidden" value="{{next_page}}" name="page"/>
    <button class="btn btn-primary" type="submit">Next</button>
  </form>

</div>


{% endblock %}

templates/product/product_detail.html
{%extends 'core/base.html' %}

{% block content%}
      <p>Product Name:{{prd.product_name}}</p>
        <p>Product Description:{{prd.product_description}}</p>
        <p>Product Price:{{prd.product_price}}</p>
        <img src="{{prd.product_image}}"/><br>
        <a href="{% url 'cart:add-cart' prd.id%}">Add To Cart  </a>    {{product}}
{% endblock %}